# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1839ab67f46ac7d78713ca3e98446ffc8fe4e359614450240869ae0503e2fe933bd50a73af8563a8ce987cc2aac826aa185894e6c8ba828005feeb7f614d0af5
  aws_secret_key: oejfejofeojf
test:
  secret_key_base: d3053fea07446f65ae0e768a541140dc26f69ec0cb8563246a1ba547524cac376ac95bf585539b79ce4a105df2cbe5f46aa54a36c53373eea629fa49ebb4ee2d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
